// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg-response.proto

package libresp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type GenericResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Result               *any.Any `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{1}
}

func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (m *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(m, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GenericResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *GenericResponse) GetResult() *any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

type MapResponse struct {
	Code                 string              `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string              `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Result               map[string]*any.Any `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MapResponse) Reset()         { *m = MapResponse{} }
func (m *MapResponse) String() string { return proto.CompactTextString(m) }
func (*MapResponse) ProtoMessage()    {}
func (*MapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{2}
}

func (m *MapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapResponse.Unmarshal(m, b)
}
func (m *MapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapResponse.Marshal(b, m, deterministic)
}
func (m *MapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapResponse.Merge(m, src)
}
func (m *MapResponse) XXX_Size() int {
	return xxx_messageInfo_MapResponse.Size(m)
}
func (m *MapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MapResponse proto.InternalMessageInfo

func (m *MapResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *MapResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *MapResponse) GetResult() map[string]*any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListResponse struct {
	Code                 string     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Result               []*any.Any `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2356d04dff83e48a, []int{3}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ListResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ListResponse) GetResult() []*any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "libresp.Response")
	proto.RegisterType((*GenericResponse)(nil), "libresp.GenericResponse")
	proto.RegisterType((*MapResponse)(nil), "libresp.MapResponse")
	proto.RegisterMapType((map[string]*any.Any)(nil), "libresp.MapResponse.ResultEntry")
	proto.RegisterType((*ListResponse)(nil), "libresp.ListResponse")
}

func init() { proto.RegisterFile("msg-response.proto", fileDescriptor_2356d04dff83e48a) }

var fileDescriptor_2356d04dff83e48a = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x24, 0x8d, 0x56, 0x7d, 0x11, 0x94, 0xc5, 0x43, 0xed, 0x29, 0x04, 0x0f, 0x41, 0xf4, 0x15,
	0xe2, 0xa5, 0x78, 0x53, 0x10, 0x2f, 0x8a, 0x90, 0x7f, 0x90, 0xa4, 0xaf, 0xe9, 0xd2, 0x74, 0x37,
	0xec, 0x47, 0x21, 0xff, 0xce, 0x9f, 0x26, 0xbb, 0x89, 0x92, 0x8b, 0x48, 0xf1, 0x36, 0x0c, 0x33,
	0x6f, 0xe6, 0x0d, 0xb0, 0x9d, 0xae, 0xef, 0x15, 0xe9, 0x56, 0x0a, 0x4d, 0xd8, 0x2a, 0x69, 0x24,
	0x3b, 0x69, 0x78, 0xe9, 0xa8, 0xf9, 0x75, 0x2d, 0x65, 0xdd, 0xd0, 0xc2, 0xd3, 0xa5, 0x5d, 0x2f,
	0x0a, 0xd1, 0xf5, 0x9a, 0x24, 0x83, 0xd3, 0x7c, 0x70, 0x31, 0x06, 0x47, 0x95, 0x5c, 0xd1, 0x2c,
	0x88, 0x83, 0xf4, 0x2c, 0xf7, 0xd8, 0x71, 0x5c, 0xac, 0xe5, 0x6c, 0xd2, 0x73, 0x0e, 0x27, 0x35,
	0x5c, 0xbc, 0x92, 0x20, 0xc5, 0xab, 0x43, 0xad, 0xec, 0x0e, 0xa6, 0x8a, 0xb4, 0x6d, 0xcc, 0x2c,
	0x8c, 0x83, 0x34, 0xca, 0xae, 0xb0, 0xaf, 0x86, 0xdf, 0xd5, 0xf0, 0x49, 0x74, 0xf9, 0xa0, 0x49,
	0x3e, 0x03, 0x88, 0xde, 0x8b, 0xf6, 0xe0, 0x94, 0xe5, 0x28, 0x25, 0x4c, 0xa3, 0x2c, 0xc6, 0x61,
	0x09, 0x1c, 0x5d, 0xc3, 0xdc, 0x4b, 0x5e, 0x84, 0x51, 0x3f, 0x89, 0xf3, 0x0f, 0x88, 0x46, 0x34,
	0xbb, 0x84, 0x70, 0x4b, 0xdd, 0x90, 0xe7, 0x20, 0xbb, 0x85, 0xe3, 0x7d, 0xd1, 0x58, 0xf2, 0x79,
	0xbf, 0xf5, 0xef, 0x25, 0x8f, 0x93, 0x65, 0x90, 0xac, 0xe0, 0xfc, 0x8d, 0x6b, 0xf3, 0xaf, 0xa1,
	0xc2, 0xbf, 0x86, 0x7a, 0xbe, 0x81, 0xa4, 0x92, 0x3b, 0xac, 0xb9, 0xd9, 0xd8, 0x12, 0xdb, 0xad,
	0xdd, 0x70, 0x83, 0xb2, 0x25, 0xa1, 0xf7, 0x95, 0xfb, 0x1d, 0xdd, 0xf3, 0xe5, 0xd4, 0x7b, 0x1f,
	0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x30, 0xfa, 0x79, 0x2c, 0x02, 0x00, 0x00,
}
